### PR TITLE
Added support for multi languages site Fixed email sender bug. Added customization of webmaster notification subject. Added the possibility to order in ASC and DESC

### PR DESCRIPTION
**Pull request by AndreaCatania**
I've added an array that contains the list of names where the system'll check to get the language required. These checks is done in $_GET, $_POST, $_COOKIE.

I've made the pull request, becouse I've used this approach to allow HashHover to works with my CMS.

### CODE REVIEW

**Comment by AndreaCatania** [comment]
## New commits
### Sender bug
I've added a modification that correct a bug when the email header is created, now the correct sender is selected.
In addition is possible to choose a custom sender by put it in the settings.php _(check the variable: **$emailSender**)_

### Notification Subject Customization
This features is very important for me because if the subject is always the same the Webmail like GMail group all this mail and lost a comment is easy.
In orther to manage it check the settings.php file on section **Webmaster notification email**

**Comment by jorgesumle** [comment]
Could you remove the trailing whitespaces? I haven't reviewed it completely, this is just one little thing I noticed.

**Comment by AndreaCatania** [comment]
which file?

**Comment by AndreaCatania** [comment]
Now is possible to set the reading order. Just check the parameter: **$readCommentsDESC** on settings.php

**Comment by jorgesumle** [comment]
Every file that you change except `hashover/scripts/writecomments.php`.

Also, another tip for future pull requests. Try to change only one thing for each pull request. If you have to make three pull requests is fine. It's easier for people to review them then.

**Comment by AndreaCatania** [comment]
Sorry but I can't see any trailing whitespaces, if you can give me a link to a precise row and file as example

**Comment by jorgesumle** [comment]
Here is a picture. The red things are trailing tabs (I noticed they were not whitespaces, but tabs)
trailing-tabs

**Comment by AndreaCatania** [comment]
Done!

**Comment by AndreaCatania** [comment]
I noticed the ordering is very buggy, But I think is wrong the approach used by this library to store the comments. My solution of ordering not works as I expected, when there are reply to a particular comment.

So I'm going to implement a parameter to block reply button as "fast fix" untill the approach of comment storing is not improved.

**Pull request closed without merging**
