### PR TITLE
Small typos in de-locale

### PR DESCRIPTION
**Pull request by prisae**
Small corrections to de-locale:
- Translation of the month "May" was wrong.
- In the Markdown description, you used 'Ihrem', which is the polite form of the colloquial 'Deinem'. However, throughout the German locale the colloquial version is used. I think in this case we can just leave it out, and therefore avoid the problem completely.
- The phrase "entweicht HTML" sounds weird. But I have to admit that I don't know how to improve it, or if there is a good possibility in German to describe 'escapes' in the computer-sense at all. Maybe leaving it out would be an alternative.

### CODE REVIEW

**Comment by jacobwb** [comment]
Thanks for the improvements!

As for "entweicht HTML", I was unsure about this as well, would something like "zeigt Code an" or "zeigt HTML", or maybe "codiert HTML zeichen" or "zu codierung HTML zeichen" be better?

**Comment by prisae** [comment]
I had a bit a look around what is used in other documentations. How about:
    "wird in HTML umgewandelt"

**Comment by jacobwb** [comment]
Hmm. You would know better than I, but it seems to me that this implies the text will be converted to HTML, the opposite of escaping, rather than that the HTML will be converted to text.

I also just noticed that in the HTML section "wird als HTML dargestellt" is used, which equally seems to imply something different than escaping.

How does something like "HTML im &lt;code&gt; wird in text umgewandelt" sound to you?

**Comment by prisae** [comment]
Yes, I chose that wording because of what you used in the HTML section, so either we would have to change both or none.

Maybe I am not sure if I am getting the English version right in the first place: It says:

    <b>, ..., escapes HTML

but isn't it the case that it actually takes &lt;b&gt; as html-tag, therefore showing the text bold? (So, actually NOT escaping html, but taking it as html?)

Then, it says:

    **bold**, ..., escapes HTML

but in this case the markup &#42;&#42;bold&#42;&#42; is translated into the html &lt;b&gt;, no?

If my assumptions are correct, wouldn't it be better to say:

    <b>, ..., are accepted HTML-tags.
    **bold**, ..., will be translated into HTML-tags

Very likely I got the whole thing wrong. If you can explain me the two cases in the case for English then I will think about the German version again.

**Comment by jacobwb** [comment]
There is some confusion here, yes.

"&lt;code&gt; escapes HTML", "\```code\``` escapes HTML" are trying to say that what is placed inside of either `<code>` tags or ` ``` ` markdown will be escaped, or converted to text. It's entirely possible that even my choice of English words is unclear and can be worded better.

Just for demonstration purposes, here are some examples.

Comments using accepted HTML:

```html
<s>Don't</s> Check out <i>my</i> <u>text</u> <b>styles.</b>
```

And comments using accepted Markdown:

```
~~Don't~~ Check out *my* _text_ **styles.**
```

Both become:

<s>Don't</s> Check out <i>my</i> <u>text</u> <b>styles.</b>

However, wrapping that text in a `<code>`  tag will convert HTML to text...

```html
<code><s>Don't</s> Check out <i>my</i> <u>text</u> <b>styles.</b></code>
```

Displaying it as-is:

&lt;s&gt;Don't&lt;/s&gt; Check out &lt;i&gt;my&lt;/i&gt; &lt;u&gt;text&lt;/u&gt; &lt;b&gt;styles.&lt;/b&gt;

Markdown is similar...

```
```~~Don't~~ Check out *my* _text_ **styles.**```
```

Displays as-is:

\~\~Don't\~\~ Check out \*my\* \_text\_ \*\*styles.\*\*

I hope I explained that decently.

**Comment by prisae** [comment]
I don't think there is a 100 % satisfying solution. It appears that very often the English word *escape* is used in German texts, without translation... The escape-character is translated to *Maskierungszeichen* in the German version of wikipedia (https://de.wikipedia.org/wiki/Maskierungszeichen). I think this leads to a good solution:

    <b>, ..., maskieren HTML
    **bold**, ..., maskieren HTML

Admittedly, it feels only slightly better than *entweichen*. At least I think it should say the same for both, *\<b\>* and for *\*\*bold\*\**-tags.

**Comment by jacobwb** [comment]
Sounds good.

**Comment by prisae** [comment]
Great, case closed, thanks a lot!

**Pull request merged**
