### PR TITLE
Allow custom root

### PR DESCRIPTION
**Pull request by aoloe**

### CODE REVIEW

**Comment by jacobwb** [comment]
I don't think this commit does what you think it does.

You are initializing those properties with `null` and checking if they are not set, when by default they are `null` and `empty ()` is more suitable. You also fail to do similar checks for this new mysterious `$parent_directory` variable. And this is all done inside a constructor, where none of the properties are even able to have any value yet.

I think what you're looking to do is...

```
$parent_directory = '/path/to/directory';

$hashover = new HashOver ();
$hashover->setup->rootDirectory = $parent_directory;
$hashover->setup->httpDirectory = '/' . basename ($parent_directory);
```

That is untested, but should work.

**Comment by aoloe** [comment]
on empty and null: an empty string (or even the string "0000") is a possible value for `rootDirectory` (no idea if it's a useful one, but a possible one...).

using `empty()` would lead to consider it as not defined, while `is_set()` and `isnull()` do not.

not sure if the null initialization automatically happens or if the value is initialized to zero.  
personally, i consider it better to initialize it to a known value and the check for it (by naturally using the `null` value in this case, since we cannot initialize it with the value returned by the path related functions).

generally speaking, it is not a good idea to leave variables undefined...

**Comment by aoloe** [comment]
`$parent_directory`: i guess i should stop making pull requests by using the web interface provided by github!  
it looked like a good idea, but too many untested errors slip through.

i'm sorry for it.

in my code i have renamed `$dirname` to `$parent_directory`.

p.s.: i checked: "0000" is not empty...

**Comment by aoloe** [comment]
i'll create a new pull request.

**Comment by aoloe** [comment]
i have modified the pull request.

**Comment by jacobwb** [comment]
> And this is all done inside a constructor, where none of the properties are even able to have any value yet.

This commit doesn't do what you think it does.

There's no point in checking for property values inside class constructors. The class properties cannot have any value until after the `__construct ()` function has executed. It also doesn't make any sense to change the root directory path this way, since it makes no sense to include files from a directory outside the directory where the `settings.php` file resides.

**Comment by aoloe** [comment]
i understand your comment about having the root being always below the settings.
it was part of the modifications i was doing for getting hashover to work in a setup where hashover is not installed at the root.
i don't use those modifications anymore / for now...

for the values not being set in the constructor: basically, you would be right, if you were not using the class variables as a configuration files. the values are manually set and are obviously in their definitive state before the constructor is called.
i will undo the changes from this commit in my code and close this pull request.

**Pull request closed without merging**
