### PR TITLE
[L10N] Proofread Spanish (es) localization

### PR DESCRIPTION
**Pull request by Roboe**
- Grammar check
- Consistency in user treatment: informal 2nd grammatical person was choosen instead of formal 3rd
- Spelling check

Also, before merging, I'd like to know how `date-time` syntax works.

### CODE REVIEW

**Comment by jorgesumle** [comment]
The corrections are good (I'm another Spanish speaker).

**Comment by jorgesumle** [comment]
@jacobwb, can you review and merge this?

**Comment by jacobwb** [comment]
Hello, sorry for the long delay.

Thank you very much for these improvements. I will be pushing new code soon, so I hope these changes will still be merge-able after, if not I will include the changes manually.

The `date-time` syntax should be read like this "%s a las %s", the first `%s` is replaced with the comment posting date and the second is replaced by the comment posting time. The specific syntax for this string can be found in the [PHP documentation](http://php.net/manual/en/function.date.php).

This is only used when the public `$usesShortDates` setting is set to `false`.

For example... "07/15/2017 a las 5:46pm"

**Comment by Roboe** [comment]
I would have liked to maintain the authorship of my commit, but whatever. Thanks for merging.

**Pull request closed without merging**
