### PR TITLE
Misc changes for easier theming of elements

### PR DESCRIPTION
**Pull request by Lux-Delux**
It would be really easier to style these if they were wrapped in a class.

My changes are a quick mock up, please suggest improvements

### CODE REVIEW

**Comment by Lux-Delux** [comment]
In general I'd say we should somehow streamline the code more regarding theming.

Perhaps even a template file for the first balloon. Because for example someone would use sections instead of divs, or divs instead of spans etc. 

Though I understand it's not easy to implement

**Comment by jacobwb** [comment]
Unfortunately, I think this work will have to wait until I remove the inline HTML and unify the JavaScript and PHP modes. Because, basically, any work that's done in the JavaScript to allow better theming has to be done again in the PHP mode. And the more code I add to the JavaScript also means more code to go through when I unify the two modes.

I posted a glimpse of my plans on Twitter a little while ago:
> https://twitter.com/tildehash/status/573274737670950912

You might not know it from that little screenshot, but the code I'm writing will allow for relatively easy swapping of tags, like you said, some people like `<div>`, and using `<span>` has the benefit of automatically making the display element inline instead of block, some people prefer the newer `<section>`, and some people might want to use `<button>` instead of `<input type="submit" ...>`.

All of that should be a matter of changing, for example...

> $div = new HTMLTag ('div', false);

Into...

> $`section` = new HTMLTag ('`section`', false);

**Comment by Lux-Delux** [comment]
Awesome, ok I'll be using my custom work arounds until the changes are in place

**Comment by Lux-Delux** [comment]
For example (sloppy code ahead :P )

`$wraps = true;
if ($wraps) {
echo $this->setup->escape_output('<div class="hashover-main-buttons">'); 
}`

**Comment by jacobwb** [comment]
Alright, the buttons in the main form at the top are now wrapped in a `<div>` tag with the class name "hashover-main-buttons". The buttons in the reply and edit forms are similarly wrapped with the class name "hashover-form-buttons".

I don't think there is a need for this to be optional. I think the rule will be that anything that does not affect how the comments look or function/behave doesn't need to be configurable. So in this case, it's not configurable. Since styling the div is completely optional, doesn't affect the default appearance, and likely doesn't get in the way at all when attempting to theme other things.

Too many "wrapping tags" obviously isn't good -- it might make the JavaScript slower -- but supporting a good minimum is absolutely necessary. Also, lots of other things should be wrapped in classed tags (perhaps `<div>` is not necessarily the best default choice, `<span>` might be better), and many things need to be given classes/ids, etc. This will be done when I remove the inline HTML.

I just don't wanna do it all twice.

**Comment by Lux-Delux** [comment]
Very nice.

Yeah there should be clear css class distinctions between a lot of elements but one thing a time, I realize code improvements/functionality are priority (as they should be)

**Pull request closed without merging**
